= Changelog

== unreleased

* Replace the strict presence requirements of some keys in models with a less aggressive method `#expected_properties?`, which allows a developer to check the presence themselves.

== 0.5.0

* Rename `ClashOfClansApi::Models::ClanWarLeagueClanMember#townhall_level` to `town_hall_level`.
* Raise the default value of the `limit` parameter of `ClashOfClansApi::Client#league_season` to 100.

== 0.4.2

* Add method `ClashOfClansApi::Models::ClanWarLeagueRound#prepared?` that indicates whether wars for the round have been created or not.

== 0.4.1

* Implement more client methods.
** `ClashOfClansApi::Client#clanwarleagues_war`
** `ClashOfClansApi::Client#clan_currentwar_leaguegroup`

== 0.4.0

* Delete removed properties.
** `ClashOfClansApi::Models::Player#versus_trophies`
** `ClashOfClansApi::Models::Player#best_versus_trophies`
** `ClashOfClansApi::Models::Player#versus_battle_wins`
** `ClashOfClansApi::Models::Clan#clan_versus_points`
** `ClashOfClansApi::Models::Clan#required_versus_trophies`
* Handle hero equipment in player models.
* Increase minimal required Ruby version to 3.0.0.

== 0.3.0

* Increase required Ruby version to 2.7.0.
* Factor out generic API access code into the new `api_frame` gem.
* Add `ClashOfClansApi::TokenClient#create_or_get_api_key_for_current_ipv4_address`.
* Add new API endpoints for clan capitals and the new builder base.
* Record test data with the `vcr` gem.
* Update existing models for new properties.
* Add models and client methods for regular clan wars.
* Rewrite tests to make supporting new endpoints easier and reduce code duplication.
* Apply many small code quality improvements.
